# Tested on `CentOS Linux release 7.6.1810 (Core)` using Ansible 2.7.5
- hosts: all
  become: yes
  vars:
    docker_config: /etc/docker/daemon.json
  tasks:

  - block:

    - name: Install RPMs
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

    - name: Add docker repo
      yum_repository:
        name: docker-ce
        description: Docer CE (Stable)
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install docker
      yum:
        name: docker-ce-18.06.2.ce
        state: present

    - name: Create needed directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
      - /etc/docker
      - /etc/systemd/system/docker.service.d
      register: required_dirs

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      when: required_dirs.changed

    - name: Create docker config
      blockinfile:
        path: "{{ docker_config }}"
        block: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2",
            "storage-opts": [
              "overlay2.override_kernel_check=true"
            ]
          }
        create: yes
      notify: Restart docker

    - name: Cleanup docker config
      lineinfile:
        path: "{{ docker_config }}"
        regexp: '^#'
        state: absent
      notify: Restart docker

    tags: setup_docker

  - block:

    - name: Disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Add kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes Repo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        #exclude: kube*

    - name: Disable selinux
      selinux:
        state: disabled

    - name: Install kubernetes packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - kubelet
      - kubeadm
      - kubectl

    - name: Enabled kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: Load needed module(s)
      modprobe:
        name: br_netfilter

    - name: Prevent packets from bypassing iptables
      sysctl:
        name: "{{ item }}"
        value: 1
      with_items:
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables

    tags: setup_kubeadm

  - block:

    - name: Set master hostname
      set_fact:
        master_hostname: "{{ (groups['all'] | sort())[0] }}"

    - name: Set master ip
      set_fact:
        master_ip: "{{ hostvars[(groups['all'] | sort())[0]]['ansible_eth1']['ipv4']['address'] }}"

    - name: Create master node
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 apiserver-advertise-address={{ master_ip }}
      register: kubeadm_init_logs
      delegate_to: "{{ master_hostname }}"

    - name: Install pod network
      shell: "{{ item }}"
      with_items:
      - kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
      - kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

    - name: Get join command
      shell: echo pass

    - name: Join nodes to cluster
      shell: echo pass

    tags: setup_kubernetes

  handlers:

  - name: Restart docker
    systemd:
      name: docker
      state: restarted