# -*- mode: ruby -*-
# vi: set ft=ruby :
# Description:
#   Kubernetes nodes eaach having /dev/sdb as second disk used for
#   /var/lib/docker.
Vagrant.configure("2") do |config|
  N = 3
  home = ENV['HOME']
  virtual_box_path = "#{home}/VirtualBox VMs"
  (1..N).each do |machine_id|
    hostname = "kube#{machine_id}"
    config.vm.define "#{hostname}" do |machine|
      machine.vm.hostname = "#{hostname}"
      machine.vm.box = "centos/7"
      machine.vm.provider "virtualbox" do |vb|
        disk = "#{virtual_box_path}/#{hostname}/docker-#{hostname}.vdi"
        vb.name = "#{hostname}"
        vb.memory = 2048
        vb.cpus = 2
	unless File.exist?(disk)
	  vb.customize ['createhd', '--filename', disk, '--size', 5 * 1024]
	end
	vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
      end
      machine.vm.network "private_network", ip: "192.168.50.#{100+machine_id}"
      # run ansible playbook on all machines when all of them are ready
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "setup_base.yml"
        end
      end
    end
  end
end
