- hosts: all
  become: yes
  vars:
    remote_ssh_user: "{{ lookup('env', 'USER') }}"
    inventory_file: inventory
    time_zone: Asia/Singapore
  tasks:

  - name: (RedHat|CentOS) Install dependencies
    yum:
      name: "{{ item }}"
      state: present
    loop:
    - libselinux-python
    when: ansible_distribution | lower == 'centos' or
          ansible_distribution | lower == 'redhat'

  - name: (Debian|Ubuntu) Install dependencies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
    - python-selinux
    when: ansible_distribution | lower == 'ubuntu' or
          ansible_distribution | lower == 'debian'

  - include_tasks: base.yml

  # - include_tasks: redhat.yml
  #   when: ansible_distribution | lower == 'centos' or
  #         ansible_distribution | lower == 'redhat'

  handlers:

  - name: Restart sshd
    service:
      name: sshd
      state: restarted
